# Generated by Django 4.2.8 on 2023-12-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bucket_remove_order_rider_order_cluster_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
