# Generated by Django 4.2.8 on 2023-12-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Maliyekkal house, Karunagappally', max_length=256),
            preserve_default=False,
        ),
    ]
